title: PortFolio
description: 포트폴리오 용 웹페이지 입니다.
author: JaeSeong Park
avatar: /img.png
email: wotjd4305@naver.com
blog: https://meorimori.tistory.com/

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ngzhio
  card: summary
logo: img.png
social:
  name: JaeSeong Park
  links:
    - https://twitter.com/ngzhio
    - https://www.facebook.com/ngzhio
    - https://github.com/wotjd4305
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
